### ISSUE TITLE
React Group Project - Kanban Setup

### ISSUE THREAD

**Issue by skyv26** [Moathal/space-x#25]
# Kanban Board Setup - SpaceX React Project.

We are a group of two people @skyv26  and @Moathal and have successfully assigned the task to each other on the board. 

[Click Here For Project Link](https://github.com/Moathal/space-x/projects/1)

**Comment by Nemwel-Boniface** [comment]
## Hello @skyv26   and @Moathal        :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job working on your project so far! :clap:
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [x] Kindly ensure that you put the correct link to the Kanban board in your issue description and request for a re-review. [This](https://github.com/Moathal/space-x/projects/1) is the correct link.
- [x] Kindly ensure that all the tasks that are labeled as "group tasks" are assigned to both teammates in the group and not left without being assigned to any member.

![image](https://user-images.githubusercontent.com/86318284/192498273-a51702ca-d2d1-4206-b9fc-8059cd521bda.png)


_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Moathal** [comment]
Made as requested.

**Comment by 1GORDON** [comment]
# Status: APPROVED 🟢 

Hi @skyv26 & @Moathal ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by skyv26** [comment]
Thank you very much @1GORDON .

Happy Coding 🥂
